/* Automatically generated by './build/build.entry.js' */

import SvgIcon from './core/packages/svgIcon/index.js';
import Alert from './core/packages/alert/index.js';
import Button from './core/packages/button/index.js';
/* 其他需要引入的文件在这里引入，暂时还没有 */

const components = [
    SvgIcon,
    Alert,
    Button
];

const install = function(Vue, opts = {}) {
    /* 需要注册的组件，指令，常量等在这里设置 */

    components.forEach(component => {
        Vue.component(component.name, component);
    });

    Vue.prototype.$STC = {
        size: opts.size || '',
        zIndex: opts.zIndex || 2000
    }
}

/* istanbul ignore if */
if(typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}
export default {
    version: '1.0.1',
    install,
    SvgIcon,
    Alert,
    Button
};
